baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Nidesso'
theme = 'nidesso'

[params]
    footer = "test"


[menu]
    [[menu.nav]]
    name = "Home"
    url = "/home"
  
    [[menu.nav]]
    name = "Team"
    url = "/team"

    [[menu.nav]]
    name = "Projekt"
    url = "/project"


    