name: Hugo GH Page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0  
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'    


      - name: Build
        run: |
         hugo -D
         mkdir tmp
         
         
         cp public/index.html public/404.html
         cp -r public/* ./tmp
       
         git pull --all
         git checkout -f build/gh-page
         git branch
         
         rm -r $( printf '%s\n' * | grep -Ewv ".git|tmp" )
         
         mv tmp/* ./
         rm -r tmp 

         touch CNAME
         echo "www.nidesso.ch" >> CNAME
         
         git config --global user.email "build@nidesso.ch"
         git config --global user.name "Build Job"
         git add .
         git commit -m "build by github action" --allow-empty
         git push
